version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'mtr-time-tracker'
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_USER: 'admin'
      MYSQL_PASS: 'parola'
    volumes:
      - /home/kalo/repos/mtr-time-tracker/mysql_data:/var/lib/mysql
  web:
    build: .
    command: python3 rest/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "9000:8000"
    depends_on:
      - db
